'use client';

import { useJobs, usePublishJob } from '@/lib/hooks/useJobs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Sparkles, Calendar, ArrowRight, CheckCircle2, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { useRouter } from 'next/navigation';

export default function GeneratedJobsPage() {
    const router = useRouter();
    const { data: jobsResponse, isLoading } = useJobs({ status: 'draft' });
    const publishJob = usePublishJob();

    const jobs = jobsResponse || [];

    const handlePublish = (jobId: string) => {
        publishJob.mutate(jobId, {
            onSuccess: () => {
                // Optionally show a toast here
                router.refresh();
            },
        });
    };

    if (isLoading) {
        return (
            <div className="flex items-center justify-center min-h-[400px]">
                <Loader2 className="h-8 w-8 animate-spin text-indigo-500" />
            </div>
        );
    }

    return (
        <div className="space-y-8">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold bg-gradient-to-r from-slate-900 via-indigo-900 to-slate-900 bg-clip-text text-transparent">
                        Generated Jobs
                    </h1>
                    <p className="text-slate-500 mt-1">Review and publish AI-generated job postings</p>
                </div>
            </div>

            {jobs.length === 0 ? (
                <Card className="border-dashed border-2 border-slate-200 bg-slate-50/50">
                    <CardContent className="flex flex-col items-center justify-center py-16 text-center">
                        <div className="w-16 h-16 rounded-full bg-indigo-50 flex items-center justify-center mb-4">
                            <Sparkles className="h-8 w-8 text-indigo-400" />
                        </div>
                        <h3 className="text-lg font-semibold text-slate-900">No generated jobs found</h3>
                        <p className="text-slate-500 max-w-sm mt-2">
                            Jobs generated by the AI agent will appear here for your review and approval.
                        </p>
                    </CardContent>
                </Card>
            ) : (
                <div className="grid grid-cols-1 gap-6">
                    {jobs.map((job) => (
                        <Card
                            key={job.id}
                            className="group hover:shadow-lg transition-all duration-300 border-indigo-100/50 overflow-hidden"
                        >
                            <div className="flex flex-col md:flex-row md:items-center gap-6 p-6">
                                <div className="flex-1 min-w-0 space-y-3">
                                    <div className="flex items-start justify-between md:justify-start gap-4">
                                        <h3 className="text-xl font-semibold text-slate-900 group-hover:text-indigo-700 transition-colors">
                                            {job.title}
                                        </h3>
                                        <Badge variant="secondary" className="bg-indigo-50 text-indigo-700">
                                            AI Generated
                                        </Badge>
                                    </div>

                                    <div className="flex flex-wrap items-center gap-4 text-sm text-slate-500">
                                        <span className="flex items-center gap-1.5">
                                            <Calendar className="h-4 w-4" />
                                            Generated {job.createdAt ? format(new Date(job.createdAt), 'PPP') : 'Recently'}
                                        </span>
                                        {job.department && (
                                            <span className="px-2 py-0.5 rounded-full bg-slate-100 text-slate-600 font-medium">
                                                {job.department}
                                            </span>
                                        )}
                                        {job.location && (
                                            <span className="px-2 py-0.5 rounded-full bg-slate-100 text-slate-600 font-medium">
                                                {job.location}
                                            </span>
                                        )}
                                    </div>

                                    <p className="text-slate-600 line-clamp-2">
                                        {job.description}
                                    </p>
                                </div>

                                <div className="flex items-center gap-3 md:border-l md:border-slate-100 md:pl-6">
                                    <Button
                                        variant="outline"
                                        onClick={() => router.push(`/dashboard/jobs/${job.id}`)}
                                        className="whitespace-nowrap"
                                    >
                                        Review Details
                                    </Button>
                                    <Button
                                        onClick={() => handlePublish(job.id)}
                                        disabled={publishJob.isPending}
                                        className="whitespace-nowrap bg-indigo-600 hover:bg-indigo-700 text-white gap-2"
                                    >
                                        {publishJob.isPending ? (
                                            <Loader2 className="h-4 w-4 animate-spin" />
                                        ) : (
                                            <CheckCircle2 className="h-4 w-4" />
                                        )}
                                        Publish Now
                                    </Button>
                                </div>
                            </div>
                        </Card>
                    ))}
                </div>
            )}
        </div>
    );
}
