"""initial_postgres_migration

Revision ID: 98b7f714713f
Revises: 
Create Date: 2026-04-16 18:31:55.996007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b7f714713f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'CANDIDATE', 'GUEST', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_candidate_profiles_id'), 'candidate_profiles', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Job title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full job description'),
    sa.Column('short_description', sa.Text(), nullable=True, comment='Short summary for social media'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='Job location (city, state, country)'),
    sa.Column('is_remote', sa.Boolean(), nullable=False, comment='Is this a remote position?'),
    sa.Column('location_type', sa.String(length=50), nullable=True, comment='on_site, remote, hybrid'),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', 'VOLUNTEER', 'FREELANCE', name='jobtype'), nullable=False, comment='Type of employment'),
    sa.Column('experience_level', sa.Enum('ENTRY_LEVEL', 'ASSOCIATE', 'MID_SENIOR', 'DIRECTOR', 'EXECUTIVE', name='experiencelevel'), nullable=True, comment='Required experience level'),
    sa.Column('department', sa.String(length=200), nullable=True, comment='Department or team'),
    sa.Column('salary_min', sa.Integer(), nullable=True, comment='Minimum salary'),
    sa.Column('salary_max', sa.Integer(), nullable=True, comment='Maximum salary'),
    sa.Column('salary_currency', sa.String(length=10), nullable=False, comment='Currency code'),
    sa.Column('salary_period', sa.String(length=20), nullable=True, comment='hourly, monthly, yearly'),
    sa.Column('salary_range', sa.String(length=200), nullable=True, comment='Formatted salary range for display'),
    sa.Column('application_url', sa.String(length=1000), nullable=True, comment='URL to apply for the job'),
    sa.Column('application_email', sa.String(length=255), nullable=True, comment='Email to send applications'),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True, comment='Application deadline'),
    sa.Column('required_skills', sa.JSON(), nullable=True, comment='Required skills'),
    sa.Column('preferred_skills', sa.JSON(), nullable=True, comment='Preferred skills'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='Detailed requirements text'),
    sa.Column('preferred_qualifications', sa.Text(), nullable=True, comment='Preferred qualifications text'),
    sa.Column('benefits', sa.JSON(), nullable=True, comment='Job benefits'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PUBLISHED', 'CLOSED', 'ARCHIVED', name='jobstatus'), nullable=False, comment='Current status'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='When the job was first published'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the job listing expires'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Hiring company name'),
    sa.Column('company_logo_url', sa.String(length=1000), nullable=True, comment='Company logo URL'),
    sa.Column('company_website', sa.String(length=1000), nullable=True, comment='Company website'),
    sa.Column('slug', sa.String(length=500), nullable=True, comment='URL-friendly slug'),
    sa.Column('meta_title', sa.String(length=200), nullable=True, comment='SEO meta title'),
    sa.Column('meta_description', sa.String(length=500), nullable=True, comment='SEO meta description'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Tags for categorization'),
    sa.Column('manager_feedback', sa.Text(), nullable=True, comment='Internal feedback from hiring manager'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Additional metadata including publications history'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='Number of views'),
    sa.Column('application_count', sa.Integer(), nullable=False, comment='Number of applications'),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created_by'), 'posts', ['created_by'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_table('user_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_integrations_id'), 'user_integrations', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW_INVITED', 'INTERVIEW_PENDING', 'INTERVIEW_IN_PROGRESS', 'INTERVIEW_COMPLETED', 'OFFER', 'REJECTED', 'HIRED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True, comment='AI compatibility score (0-100)'),
    sa.Column('ai_feedback', sa.Text(), nullable=True, comment='AI summary of the application'),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email_delivery_status', sa.String(length=50), nullable=True, comment='Email status: PENDING, SENT, FAILED'),
    sa.Column('email_logs', sa.Text(), nullable=True, comment='Failure reasons or SMTP logs'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_email_delivery_status'), 'applications', ['email_delivery_status'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False, comment='Secure token for guest access'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'CODING', 'SUBMITTED', 'COMPLETED', 'EXPIRED', name='interviewstatus'), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False, comment='Full chat history'),
    sa.Column('state', sa.JSON(), nullable=False, comment='Internal AI state (current skill, stage, etc)'),
    sa.Column('code_submission', sa.Text(), nullable=True, comment='Final code submission if applicable'),
    sa.Column('programming_language', sa.String(), nullable=True, comment='Programming language selected for coding challenge'),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True, comment='URL/Path to screen recording file'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_path', sa.String(), nullable=True, comment='Path to stored screen recording video'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_token'), 'interview_sessions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_token'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_email_delivery_status'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_user_integrations_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_by'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_candidate_profiles_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
